apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  labels:
    app: nodejs-app
  annotations:
    # This tells AWS to create a Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nodejs-app