{
 "title": "Node.js App Metrics",
 "tags": [
  "nodejs",
  "devops-project"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(root_access_total[1m]))",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "Event Loop Lag (P99)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Resident Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "RSS Memory"
    }
   ]
  },
  {
   "title": "Active Handles & Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "Handles" },
    { "expr": "nodejs_active_resources_total", "legendFormat": "Resources" }
   ]
  }
 ]
}